crop_size: 256
test_crop_size: 1024
val_crop_size: 1024
num_crops_per_image: 2
batch_size_clean: 1
batch_size_noisy: 4
arch_enc: Balle
arch_dec: Balle
transfer_function: None
transfer_function_valtest: None
arbitrary_proc_method: opencv
match_gain: input
debug_options:
  - 1thread